# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jinhuoqudao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u6e20\u9053\u5546',
                'verbose_name_plural': '\u6e20\u9053\u5546',
            },
        ),
        migrations.CreateModel(
            name='Yifu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
                ('tiaomahao', models.CharField(max_length=32, verbose_name='\u6761\u7801\u53f7')),
                ('guige', models.CharField(max_length=32, verbose_name='\u89c4\u683c')),
                ('yanse', models.CharField(max_length=32, verbose_name='\u989c\u8272')),
                ('qudao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dzz.Jinhuoqudao', verbose_name='\u6e20\u9053')),
            ],
            options={
                'verbose_name': '\u8d27\u7269\u4fe1\u606f',
                'verbose_name_plural': '\u8d27\u7269\u4fe1\u606f',
            },
        ),
    ]
