# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzz', '0003_yifu_chengben'),
    ]

    operations = [
        migrations.AddField(
            model_name='yifu',
            name='dsq',
            field=models.CharField(default='', max_length=8, null=True, verbose_name='\u591a\u5c11\u94b1\u8bb0\u4e00\u5206'),
        ),
        migrations.AddField(
            model_name='yifu',
            name='jifen',
            field=models.CharField(default='', max_length=8, null=True, verbose_name='\u79ef\u5206'),
        ),
    ]
