# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzz', '0005_auto_20161008_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chukulog',
            name='time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='rukulog',
            name='time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4'),
        ),
    ]
