# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzz', '0006_auto_20161008_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jiagewenjian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('uploadfile', models.FilePathField(verbose_name='\u6210\u672c\u4ef7\u683c\u6587\u4ef6')),
                ('caozuoren', models.CharField(max_length=16, verbose_name='\u6267\u884c\u4eba')),
            ],
        ),
        migrations.AlterField(
            model_name='yifu',
            name='chengben',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='\u6210\u672c'),
        ),
        migrations.AlterField(
            model_name='yifu',
            name='dsq',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='\u8bb0\u4e00\u5206'),
        ),
        migrations.AlterField(
            model_name='yifu',
            name='jiage',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='\u4ef7\u683c'),
        ),
        migrations.AlterField(
            model_name='yifu',
            name='jifen',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='\u79ef\u5206'),
        ),
    ]
