# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzz', '0007_auto_20161008_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiagewenjian',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='wenjianming'),
        ),
        migrations.AlterField(
            model_name='jiagewenjian',
            name='uploadfile',
            field=models.FileField(upload_to='./upload/', verbose_name='\u6210\u672c\u4ef7\u683c\u6587\u4ef6'),
        ),
    ]
