# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzz', '0008_auto_20161008_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huiyuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='\u59d3\u540d')),
                ('sex', models.BooleanField(choices=[(1, '\u5973'), (0, '\u7537')], default=1, verbose_name='\u6027\u522b')),
                ('cellphone', models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='\u624b\u673a\u53f7')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='\u751f\u65e5')),
                ('jifen', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u79ef\u5206')),
            ],
        ),
        migrations.AlterModelOptions(
            name='jiagewenjian',
            options={'verbose_name': '\u4ef7\u683c\u6587\u4ef6', 'verbose_name_plural': '\u4ef7\u683c\u6587\u4ef6'},
        ),
        migrations.AlterField(
            model_name='jiagewenjian',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='\u6587\u4ef6\u540d'),
        ),
    ]
