# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzz', '0009_auto_20161009_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='huiyuan',
            options={'verbose_name': '\u4f1a\u5458', 'verbose_name_plural': '\u4f1a\u5458'},
        ),
        migrations.AddField(
            model_name='huiyuan',
            name='last_xiaofei',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u6700\u8fd1\u4e00\u6b21\u6d88\u8d39\u65f6\u95f4'),
        ),
    ]
