# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dzz', '0013_huiyuan_beizhu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xiaofeijilu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jifen', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u79ef\u5206')),
                ('xiaofei', models.DateTimeField(blank=True, null=True, verbose_name='\u6d88\u8d39\u65f6\u95f4')),
                ('xiaofeijine', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u6d88\u8d39\u91d1\u989d')),
                ('beizhu', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('fapiao', models.BooleanField(choices=[(1, '\u5df2\u9886\u53d6'), (0, '\u672a\u9886\u53d6')], default=0, verbose_name='\u53d1\u7968\u5df2\u9886\u53d6')),
            ],
            options={
                'verbose_name': '\u4f1a\u5458',
                'verbose_name_plural': '\u4f1a\u5458',
            },
        ),
        migrations.AddField(
            model_name='huiyuan',
            name='shengrizengpin',
            field=models.BooleanField(choices=[(1, '\u5df2\u9886\u53d6'), (0, '\u672a\u9886\u53d6')], default=0, verbose_name='\u751f\u65e5\u5956\u52b1\u5df2\u9886\u53d6'),
        ),
        migrations.AddField(
            model_name='xiaofeijilu',
            name='huiyuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dzz.Huiyuan', verbose_name='\u4f1a\u5458'),
        ),
        migrations.AddField(
            model_name='xiaofeijilu',
            name='yifu',
            field=models.ManyToManyField(blank=True, null=True, related_name='yifu', to='dzz.Yifu', verbose_name='\u6240\u8d2d\u7269\u54c1'),
        ),
    ]
