# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzz', '0014_auto_20161009_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xiaofeijilu',
            options={'verbose_name': '\u6d88\u8d39\u8bb0\u5f55', 'verbose_name_plural': '\u6d88\u8d39\u8bb0\u5f55'},
        ),
        migrations.RenameField(
            model_name='xiaofeijilu',
            old_name='xiaofei',
            new_name='xiaofeishijian',
        ),
        migrations.AlterField(
            model_name='xiaofeijilu',
            name='yifu',
            field=models.ManyToManyField(blank=True, related_name='yifu', to='dzz.Yifu', verbose_name='\u6240\u8d2d\u7269\u54c1'),
        ),
    ]
