# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dzz', '0016_auto_20161009_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xiaofeijilu',
            options={'verbose_name': '\u6536\u94f6', 'verbose_name_plural': '\u6536\u94f6'},
        ),
    ]
