# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzz', '0017_auto_20161010_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='huiyuan',
            name='touxiang',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='jiagewenjian',
            name='filename',
            field=models.CharField(choices=[('1', '\u552e\u4ef7\u8ba1\u7b97'), ('0', '\u6279\u91cf\u5165\u5e93')], default='1', max_length=16, verbose_name='\u6587\u4ef6\u540d'),
        ),
        migrations.AlterField(
            model_name='jiagewenjian',
            name='uploadfile',
            field=models.FileField(upload_to='./', verbose_name='\u6210\u672c\u4ef7\u683c\u6587\u4ef6'),
        ),
    ]
