# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import dzz.models


class Migration(migrations.Migration):

    dependencies = [
        ('dzz', '0018_auto_20161012_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yifu',
            options={'ordering': ['-sold'], 'verbose_name': '\u8d27\u7269\u4fe1\u606f', 'verbose_name_plural': '\u8d27\u7269\u4fe1\u606f'},
        ),
        migrations.AddField(
            model_name='yifu',
            name='sold',
            field=models.BooleanField(default=0, verbose_name='\u662f\u5426\u5356\u6389'),
        ),
        migrations.AddField(
            model_name='yifu',
            name='uploadfile',
            field=models.FileField(default='default.png', upload_to='./', verbose_name='\u56fe\u7247'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='huiyuan',
            name='last_xiaofei',
            field=models.DateTimeField(blank=True, default=dzz.models.yestoday, null=True, verbose_name='\u6700\u8fd1\u4e00\u6b21\u6d88\u8d39\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='jiagewenjian',
            name='uploadfile',
            field=models.FileField(blank=True, null=True, upload_to='./', verbose_name='\u6210\u672c\u4ef7\u683c\u6587\u4ef6'),
        ),
    ]
