# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzz', '0020_auto_20161022_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huiyuan',
            name='last_xiaofei',
        ),
        migrations.RemoveField(
            model_name='huiyuan',
            name='last_xiaofeijine',
        ),
        migrations.RemoveField(
            model_name='huiyuan',
            name='zongxiaofeicishu',
        ),
        migrations.RemoveField(
            model_name='huiyuan',
            name='zongxiaofeijine',
        ),
        migrations.AlterField(
            model_name='xiaofeijilu',
            name='jifen',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u83b7\u5f97\u79ef\u5206'),
        ),
    ]
